version: "3"
services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - database

  frontend:
    build:
      context: ./frontend/curriculumvitae
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  # database:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=your_db_user
  #     - POSTGRES_PASSWORD=your_db_password
  #     - POSTGRES_DB=your_db_name
